name: Deploy to AWS

on:
    push:
        branches:
            - master # Change this to your branch if different
        paths:
            - "packages/backend/**" # Trigger only when there are changes in the packages/backend folder

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 # This step checks out the repository's code

            - name: SSH and deploy
              env:
                  AWS_SSH_PRIVATE_KEY: ${{secrets.AWS_SSH_PRIVATE_KEY}}

              run: |
                  echo "$AWS_SSH_PRIVATE_KEY" > keyfile
                  chmod 600 keyfile
                  mkdir -p ~/.ssh
                  cd known_hosts ~/.ssh/known_hosts

                  ssh -t -i keyfile ${{secrets.AWS_SSH_USERNAME}}@${{secrets.AWS_SSH_HOST}} "sudo bash ~/deploy.sh"

# Other method
# run: |
#     echo "$SSH_PRIVATE_KEY" > keyfile
#     chmod 600 keyfile
#     mkdir -p ~/.ssh
#     cd known_hosts ~/.ssh/known_hosts
#     ssh -t -i keyfile ubuntu@ec2-13-54-33-149.ap-southeast-2.compute.amazonaws.com "sudo bash "

#  ${{ secrets.AWS_SSH_PRIVATE_KEY }}
# ${{secrets.AWS_SSH_USERNAME}}@${{secrets.AWS_SSH_HOST}}
